language: node_js
node_js:
- node
before_install: npm i -g npm@latest;
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
- npm run dist
after_deploy:
- sh ./scripts/update-release.sh
deploy:
  provider: npm
  email: license@triple-it.nl
  api_key:
    secure: pXQXQFI0oTJjCC46VZ9DIX1NDoeC8li+1p9c37K3nMELAZZpKrl90ww3Kj33XGUQJAA2uyEk7TZkq7DhWC7v3JAu6H1L0TfNEz+BzNTy2TRqsowuZ1Xg53N2Zs/paVHoVczPbPE7XqgjPh2o5JQi0g1UAD4Rx3phyqv8ggpQrUeJVT6W56qOpF0/UZhrLok1GoUU53LwarMyFm2Mz2AkehmJo99uE/oamaHyJ7b50OF/s2BpLbnGbxSwgYSYJ5o/UObfqYyBmMl3SbkUw4nM7d8TSpHDqrHwo8k08ojDbA2boNA8XK3KzjSOZre6IrNVmp1yx37MiZZUuxst+/N6OI5xL5VOJyeF+lnjUQWIrOJunes5ROmiPxby/8T51SMbke22cRbFJJQfkd7reGhKWrVZZH8KfdcnxS+KdsYRqysZ+CD76HYmun/3gmC3OXTtRTdk74Ag8bnlFORAeKCuUuX3EiqJlmcIfB9tnvK4vFFixu29znIMkk/SvyGYLI6CoGH8DlVWAQh1V+fPAA6UjHqXFUIINmItPEYSDFRBxQSUfNYMbDfW4EQX+Od7oCAbNjiO2ZtQsLUCFwJNxdyOxnq7BQH7Zf915wWWepODBovyp5pbZH3ZPVi4vpvgIOI2yHPB/pUhyLiU74bp0W/wao30HUvGjWCg7doflYaaOGc=
  on:
    tags: true
    repo: meisterplayer/media-basemedia
env:
  global:
  - secure: Srf22hPaUHYmeGwhMqt0PoRoDi92q7tHgFMElkt2wmV2wyGNA0BoiQDK8zb/Ozo8c+9aqHWiesri7TTosyLEfmwUAej3+xDf0vgRW0X8lBPW1HLiIrROgxNbCBCDnuHfW87FVqk35Ow9ldX/aWflwvhqpihNT6Kj23zE6vOMDvcfu5TnFzlfF0UGjI5zur4doXf6xdRaLdQRPNRAAuU+BfgELxYyTT2Vgt/ywfIQghFQcRK8MmGWJrMghbvR8Rw14dgFO1c5XgHJSO0DPbJ2N90qXN4qMMBxUxqESGQ3q6qetV4S+ScSYNjaIssiKaeObMoTjYj/SmXwCc5qk4eAT3k2zuIUGV+MTz81hY0AIh0Pl8lPsGCUyYP8Q7V1/GoDWN8PppHZRuMFdRuXrb/Bh+TyfaG5armhzzdTbKt7INXj6jQX8MMzP9FFtvQTG7FRcvaaFxK4vCuup3cdmqsQY4rsqFzsPx4Jf3i603yfySOTX18+LI/UOvsVyCk9HtLdJNfoouqzYV1vl4FQ5YPby6K5fvZjcJqMy6CUFopDlzzvL8mIrh7+AR/G98L26D2aAy55sNiYqBOhfloehgGfgnZFlxhDl8xCe5PPq22oImbJC2PYzsHgKAz2tHj6xyy/HS3KYjLSM5OV//qik0CRgghfDhOoQegQgaNLDSvVQZ0=
  - secure: e4bLPN0wUnNTy7dR2puTcxVeukXI4LVqNZ+4qvbjHkVbrqPG90/NNSa8ULrffU654qO8aZplgMXIUJZ7ybxRiyGmQcuBEcF74zAMsm1qNSmOo31Drapir3+5utX97f1OO8IpnNuGcSCqbyTeEC31a8VuqiSlvCgAOQ4Lmfppc/6f9AN3omdhZWNWGZt4PcREqcLeoZfcAK33Ur/gjyl7fUtYW8uE/VEWncI133Tyjfglnf1BUhiEkuE8EIBKnMyjE/r8JNmatyr5sWqQ9rppWdh1bYpkHwj1jH4lXKVs3JOCbMBQy3a2yvzuEMaHgNqzABhK9Mke7JVLBY8COixlOalc2ghsn9WcYtRgIBFLfK0SIfjvn6XmjwIqy78OOQsLSz9ctCrgzjuiB6rVKCM0nAPhpf9Rx86EzclOOBiiVwhf8q1JV0D78rgUO6WLr+eMmStukQDVzB6itYKypkRdAyesDDT/sKfxO+0lxXXhMtYyQwkxkGwfkWAlURJLSGwFhMkPkPFNwTzosNBdRJWttihqZ08W8aHmEOep+vN8MSRzNDDVSYgRubHABWSGIjji1S2XsDZYz4ecnFw0ohG1UuT89B6yb5IowCQ00iQtv7XuRhiDHeIfZusuj0JGBnPWBmFDZbvv5pKYqSuWmthvNFbMIad4/OVGRn+Qj/v9/T0=
notifications:
  slack:
    rooms:
      secure: hKJuLa8ZhLpWcMO4jBf4Ik8+kffM+eFzJFEgswKoS/jyLx5XiJJKhS4/4gFtRYb8bihrAJ0ekHiH17RoE1YoxQSKISbzN8Qp83JOAHysnBC2VxfV6kAGxlP4yHD2fOF9c6UfAKsqD5ZkhafSh+6gd72Qzf7E3zIQEoFZDnNLaWiY/Fr+UQNwbosoyIScGliZHD75AFXWvoBQYAZgo5fym6A5KilaZnN9YKzN1sLnvH7oe9EraMQ4LXwHVhBUNtwm7jezgavrZ8/NQFQBysVDkB0vEfkBxNgRQ5YObLQl8LJHjv6Akw56/uBb827n5Cmc64kXQrHI1+hS4J6LFwYOIeCWwi/UU8VbTL7R2lETitqO+fmZJHiR5CWE2rbqGF4YXBx6X2/miqdeEkLqxlbgdIep2yXbrP81ZBVFQU2pu0XY/4cr7GaQ1DaRoqs7zZsUzpkEb2LtW3S2751XqH7RdJErdwQt2myK2Idz19MKhEwF8DZf9M/RfkWUicOHzYz4nfFbWB04mTGxv7evy5iWli+7HqckjNESi9e6v2ojOcfcAylG8Hoa2oY0M5nKAWCXC4IkWtWmacI7Ugb6e3hUnCqsOa41UlvBJbRZBUs1FP8PnzB4rVWhJsnVdejCXx7VcEpeVF3+jqXzIMI3zzjjttucctWIcBmIIzgFh/LxEEI=
    on_success: always
    on_failure: always
    template: |-
      Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_name}@%{branch} by %{author}
      %{result} in %{duration}
      %{commit_subject}
